admn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from admn import views 

urlpatterns = [
    # path('patient/', include(('patient.urls', 'patient'), namespace='patient')),
    path('ad_Product',views.ad_Product,name='ad_Product'),
    path('ad_varient/<int:id>',views.ad_varient,name='ad_varient'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('show_Product',views.show_Product,name='show_Product'),
    path('delete',views.delete_item,name='delete-item'),
    path('block',views.block,name='block'),
    path('unblock',views.unblock,name='unblock'),
    path('show_users',views.show_users,name='show_users'),
    path('show_doct',views.show_doct,name='show_doct'),
    path('delet_varit/<int:id>',views.delet_varit,name='delet_varit'),
    path('del_va/<int:id>',views.del_va,name='del_va'),
    path('edit_prod/<int:id>',views.edit_prod,name='edit_prod'),
    path('pat_up',views.pat_up,name='pat_up'),
    path('delet_users',views.delet_users,name='delet_users'),
    path('doc_up',views.doc_up,name='doc_up'),
    path('catagory',views.catagory,name='catagory'),
    path('catagory_delet/<int:id>',views.catagory_delet,name='catagory_delet'),
    path('catagory_edit/<int:id>',views.catagory_edit,name='catagory_edit'),
    path('add_catagory',views.add_catagory,name='add_catagory'),
    path('medicine_type',views.medicine_type,name='medicine_type'),
    path('add_medicine_type',views.add_medicine_type,name='add_medicine_type'),
    path('medicine_delet',views.medicine_delet,name='medicine_delet'),
    path('medicine_type_edit/<int:id>',views.medicine_type_edit,name='medicine_type_edit'),
    path('search',views.search,name='search'),
    path('month',views.monthly_sales_report,name='month'),
    path('day',views.daily_sales_report,name='day'),
    path('today',views.today_report,name='today'),
    path('week',views.weekly_report,name='week'),
    path('year',views.yearly_report,name='year'),
    path('download',views.download,name='download'),
    path('admin_order',views.admin_order,name='admin_order'),
    path('admin_order_refund',views.admin_order_refund,name='admin_order_refund'),
    path('admin_order_specific',views.admin_order_specific,name='admin_order_specific'),
    path('admin_c',views.admin_ord_c,name='admin_c'),
    path('get_subcategories/', views.get_subcategories, name='get_subcategories'),
    path('orderstatus',views.orderstatus,name='orderstatus'),
    path('refundstatus',views.refundstatus,name='refundstatus'),
    path('order_summery<int:id>',views.order_summery,name='order_summery'),
    path('coupn',views.coupn,name='coupn'),
    path('coupnedit/<int:id>',views.coupnedit,name='coupnedit'),
    path('coupndelete',views.coupndelete,name='coupndelete'),
    path('coupnshow',views.coupnshow,name='coupnshow'),
    path('sales_search',views.sales_search,name='sales_search'),
    path('department',views.department_show,name='department'),
    path('department_add',views.department_add,name='department_add'),
    path('department_edit/<int:id>',views.department_edit,name='department_edit'),
    path('department_delete',views.department_delete,name='department_delete'),







]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
app_name='home'

from django.contrib import admin
from django.urls import path,include
from home import views

urlpatterns = [
    # path('adm/',include('admn.urls')),
    path('',views.home,name='home'),
    path('contact',views.contact,name='contact'),
    path('about',views.about,name='about'),
    path('docter',views.docter,name='docter'),
    path('department',views.department,name='department'),
    path('signin',views.signin,name='signin'),
    path('lout', views.lout, name='lout'),
    path('item/',views.item,name='item'),
    path('medicine/<str:med>',views.medicine,name='medicine'),
    # path('tablet',views.tablet,name='tablet'),
    # path('capsule',views.capsule,name='capsule'),
    # path('syrup',views.syrup,name='syrup'),
    # path('oiment',views.oiment,name='oiment'),
    # path('powder',views.powder,name='powder'),
    # path('gel',views.gel,name='gel'),
    path('checkout',views.checkout,name='checkout'),
    path('order/<int:item>',views.order,name='order'),
    path('cart',views.cart,name='cart'),
    path('decr/<int:id>',views.decr,name='decr'),
    path('incr/<int:id>',views.incr,name='incr'),
    path('delet_cartItem/<int:id>',views.delet_cartItem,name='delet_cartItem'),
    path('add_cart/<int:id>',views.add_cart,name='add_cart'),
    path('product_page/<int:id>',views.product_page,name='product_page'),
    path('forgotP/',views.forgetP,name='forgotP'),
    path('changeP/<str:token>',views.changeP,name='changeP'),
    path("index", views.index, name="index"),
    path('adres',views.adres,name='adres'),
    path('remark/<int:id>',views.edit_address,name='remark'),
    path('delete_address',views.delete_address,name='delete_address'),
    path('coupon',views.coup,name='coupon'),
    path('delet_session',views.delete_session,name='delet_session'),
    path('high/<str:item>', views.high, name='high'),
    path('low/<str:item>', views.low, name='low'),
    path('success/',views.success,name='success'),
    path('verify_otp',views.verify_otp,name='verify_otp'),
    path('verify_email/<str:id>',views.verify_email,name='verify_email'),
    path('payment_cancel/<int:id>',views.payment_cancel,name='payment_cancel'),
    path('verification',views.verification,name='verification'),
    
    # path('hat',views.message,name='hat'),
     
]

hosp_mng/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('adm/',include('admn.urls')),
    path('Patient/',include('patient.urls')),
    path('docter/',include('docter.urls')),
    path('',include('home.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

patient/urls.py
app_name='patient'

from django.contrib import admin
from django.urls import path,include
from patient import views

urlpatterns = [
    # path('adm/',include('admn.urls')),
    path('Pat_signup',views.Pat_signup,name='Pat_signup'),
    path('Pat_dashboard',views.Pat_dashboard,name='Pat_dashboard'),
    path('appoiment/<int:id>',views.appoiment,name='appoiment'),
    path('Patient_appoiment',views.Patient_appointment,name='Patient_appoiment'),
    path('treatment',views.treat,name='treatment'),
    path('get_available_time_slots/', views.get_available_time_slots, name='get_available_time_slots'),
    path('pat_chat',views.pat_chat,name='pat_chat'),
    path('adres/<int:id>',views.adres,name='adres'),
    path('edit_adres/<int:id>/<int:item>',views.edit_adres,name='edit_adres'),
    path('delete_adres/<int:id>/<int:item>',views.delete_adres,name='delete_adres'),
    path('check/<int:id>',views.check,name='check'),
    path('copn/<int:id>',views.copn,name='copn'),
    path('d_order/<int:id>',views.d_order,name='d_order'),
    path('invoice/<int:id>',views.invoice,name='invoice'),
    path('ord',views.ord,name='ord'),
    path('ord_hys',views.ord_hys,name='ord_hys'),
    path('cancel_order',views.cancel_order,name='cancel_order'),
    path('refund/<int:id>',views.refund,name='refund'),
    path('p_profile',views.p_profile,name='p_profile'),
    path('ord_success/',views.ord_success,name='ord_success'),
    path('pay_cancel/<int:id>/<int:item>',views.pay_cancel,name='pay_cancel'),
    path('delet_coupen/<int:id>',views.delete_coupen,name='delet_coupen'),
    path('exam',views.exam,name='exam'),

   







    

]

home/views.py
from django.shortcuts import render,HttpResponse
from django.db.models import Prefetch
from admn.models import Product,varient,coupen
from django.shortcuts import render,redirect
from .models import User
from admn.forms import pform,vform
from django.contrib.auth import logout,login
from django.views.decorators.cache import cache_control
# from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from docter.models import DoctorProfile
from patient.models import patientProfile,wallet
from admn.models import Product,varient,Medicine_type
from django.db.models import Prefetch
from patient.views import Pat_dashboard 
from django.core.mail import send_mail
import uuid
from datetime import datetime, timedelta
from patient.models import Address
from .models import Cart,CartItem,Order,orderItem
from decimal import Decimal
from .forms import Patient_form
from django.conf import settings
from django.db.models import Subquery, OuterRef
from django.core import serializers
import razorpay
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django_otp import devices_for_user
# from django_otp.plugins.otp_totp.models import TOTPDevice
from twilio.rest import Client
import random
from django.contrib import messages
from django.core.mail import EmailMessage


# User=settings.AUTH_USER_MODEL
# Create your views here.




@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def home(request):
    return render(request,'index.html')

def contact(request):
    return render(request,'cont.html')

def about(request):
    return render(request,'cont.html')

def docter(request):
    return render(request,'docindex.html')

def department(request):
    return render(request,'depart.html')

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def item(request):
    product=Product.objects.filter(catagory=1).prefetch_related(Prefetch('item',queryset=varient.objects.all()))
    # print(product)
    cate=Medicine_type.objects.filter(medicine_type=None).prefetch_related(Prefetch('subcate',queryset=Medicine_type.objects.all()))
        # context={'page':'ad-mg'}
    context={'item_list':product ,'item':'none','category':cate,}
    return render(request,'shop.html',context)
def medicine(request,med):
    product=Product.objects.filter(medicine_type__name=med,catagory=1).prefetch_related(Prefetch('item',queryset=varient.objects.all()))
    cate=Medicine_type.objects.filter(medicine_type=None).prefetch_related(Prefetch('subcate',queryset=Medicine_type.objects.all()))
    context={'item_list':product,'category':cate, 'item':med}
    return render(request,'shop.html',context)
# def tablet(request):
#     product=Product.objects.filter(medicine_type__name='tablet',catagory=1).prefetch_related(Prefetch('item',queryset=varient.objects.all()))
#     context={'item_list':product, 'item':'tablet'}
#     return render(request,'shop.html',context)
# def capsule(request):
#     product=Product.objects.filter(medicine_type__name='capsule',catagory=1).prefetch_related(Prefetch('item',queryset=varient.objects.all()))
#     context={'item_list':product ,'item':'capsule'}
#     return render(request,'shop.html',context)
# def syrup(request):
#     product=Product.objects.filter(medicine_type__name='syrup',catagory=1).prefetch_related(Prefetch('item',queryset=varient.objects.all()))
#     context={'item_list':product ,'item':'syrup'}
#     return render(request,'shop.html',context)
# def oiment(request):
#     product=Product.objects.filter(medicine_type__name='powder' and 'gel' ,catagory=1).prefetch_related(Prefetch('item',queryset=varient.objects.all()))
#     context={'item_list':product, 'item':'oinment'}
#     return render(request,'shop.html',context)
# def powder(request):
#     product=Product.objects.filter(medicine_type__name='powder',catagory=1).prefetch_related(Prefetch('item',queryset=varient.objects.all()))
#     context={'item_list':product, 'item':'powder'}
#     return render(request,'shop.html',context)
# def gel(request):
#     product=Product.objects.filter(medicine_type__name='gel',catagory=1).prefetch_related(Prefetch('item',queryset=varient.objects.all()))
#     context={'item_list':product ,'item':'gel'}
#     return render(request,'shop.html',context)

def high(request,item):
    cate=Medicine_type.objects.filter(medicine_type=None).prefetch_related(Prefetch('subcate',queryset=Medicine_type.objects.all()))

    if item=='none':
        subquery = varient.objects.filter(product=OuterRef('pk')).order_by('price').values('price')[:1]
        product = Product.objects.filter(catagory=1).annotate(min_price=Subquery(subquery)).order_by('min_price')
    else:
        subquery = varient.objects.filter(product=OuterRef('pk')
        ).order_by('price').values('price')[:1]
        product = Product.objects.filter(medicine_type__name=item, catagory=1).annotate(
        min_price=Subquery(subquery)
        ).order_by('min_price')
    context={'item_list':product ,'item':item,'category':cate,}
    return render(request,'shop.html',context)
def low(request,item):
    cate=Medicine_type.objects.filter(medicine_type=None).prefetch_related(Prefetch('subcate',queryset=Medicine_type.objects.all()))
    if item=='none':
        subquery = varient.objects.filter(product=OuterRef('pk')).order_by('price').values('price')[:1]
        product = Product.objects.filter(catagory=1).annotate(min_price=Subquery(subquery)).order_by('-min_price')
    else:    
        first_variant_subquery = varient.objects.filter(product=OuterRef('pk')).order_by('price').values('price')[:1]
        product = Product.objects.filter(medicine_type__name=item , catagory=1).annotate(max_price=Subquery(first_variant_subquery)).order_by('-max_price')
    
    context={'item_list':product ,'item':item,'category':cate}
    return render(request,'shop.html',context)

@cache_control(no_cache=True, must_revalidate=True, no_store=True) 
def product_page(request,id):
    product=Product.objects.filter(id=id).prefetch_related(Prefetch('item',queryset=varient.objects.all()))
    print(product)
    context={'product':product}
    return render(request,'product-details.html',context)


  
# @cache_control(no_cache=True, must_revalidate=True, no_store=True)
def signin(request):
    response = HttpResponse('login success.')
    if request.user.is_authenticated:
        if request.user.is_superuser:
            return redirect('dashboard')
        if request.user.is_patient:
            person=patientProfile.objects.get(user_id=request.user.id)
            if person.email_verify is False:
                         user=request.user
                         email_otp(user)
                         return redirect('home:verify_email') 
                    
                    
            elif person.is_verify is False:
                         user=request.user  
                         send_otp(user)
                         return redirect('home:verify_otp')
                    
                    
                         
            else:     
                       if request.user.block is False:
                            return redirect('patient:Pat_dashboard')

                       messages.error(request,'User is block by admin') 
                       return redirect('home:signin')
            # if request.user.block is False:
            #     return redirect('patient:Pat_dashboard')

            # messages.error(request,'User is block by admin') 
            # return redirect('home:signin')

        if request.user.is_docter:
            if request.user.block is False:
                return redirect('docter:doc_dashboard')
        
            messages.error(request,'User is block by admin')
            return redirect('home:signin')



    
    else:    
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            # remember=request.POST.get('remember')
            if username == '' and password == '':
                    messages.error(request, "Username and password can't be blank")
                    return redirect('home:signin')
    
            user = authenticate(username=username, password=password)
            if user is None:
                messages.error(request, 'No such user Please check Furthor more')
                return render(request, 'login.html')
            if user is not None:
                
                if user.is_superuser:
                    login(request, user)    
                    return redirect('dashboard')
                
                if user.is_patient:
                    person=patientProfile.objects.get(user_id=user.id)
                  
                    if  person.email_verify is False:
                         user_id=user.id
                         email_otp(user_id)
                         return redirect('home:verify_email',user_id) 
                    
                    
                    # elif person.is_verify is False:
                    #      user=user  
                    #      send_otp(user)
                    #      return redirect('home:verify_otp')
                    
                    
                         
                    else:
                       login(request, user)    
                       if request.user.block is False:
                            return redirect('patient:Pat_dashboard')

                       messages.error(request,'User is block by admin') 
                       return redirect('home:signin')

                if user.is_docter:
                    person=DoctorProfile.objects.get(user_id=user.id)
                  

home/templates/base.html
<!DOCTYPE html>
<html lang="zxx">

<head>
    {% load static%}
    <meta charset="UTF-8">
    <meta name="description" content="Ashion Template">
    <meta name="keywords" content="Ashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hospital Management</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'Prod/css/Pd_bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Prod/css/Pd_font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Prod/css/Pd_elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Prod/css/Pd_jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Prod/css/Pd_magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Prod/css/Pd_owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Prod/css/Pd_slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Prod/css/Pd_style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="offcanvas__close">+</div>
        <ul class="offcanvas__widget">
            <li><span class="icon_search search-switch"></span></li>
            <li><a href="#"><span class="icon_heart_alt"></span>
                <div class="tip">2</div>
            </a></li>
            <li><a href="#"><span class="icon_bag_alt"></span>
                <div class="tip">2</div>
            </a></li>
        </ul>
        <div class="offcanvas__logo">
            <!-- <a href="./index.html"><img src="img/logo.png" alt=""></a> -->
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="offcanvas__auth">
            <a href="#">Login</a>
            <a href="#">Register</a>
        </div>
    </div>
    <!-- Offcanvas Menu End -->

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-3 col-lg-1">
                    <div class="header__logo">
                        <a href="{% url 'home:home'%}">
                            <img src="{% static 'assets/img/logo/logo.png' %}" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-7 ">
                    <nav class="header__menu  float-right mr-5 pr-5">
                        <ul>                            
                            <li><a href="{% url 'home:item' %}">Product</a></li>
                            <li><a href="{% url 'home:docter' %}">Doctors</a></li>
                            <!-- <li><a href="#">Pages</a>
                                <ul class="dropdown">
                                    <li><a href="./product-details.html">Product Details</a></li>
                                    <li><a href="./shop-cart.html">Shop Cart</a></li>
                                    <li><a href="./checkout.html">Checkout</a></li>
                                    <li><a href="./blog-details.html">Blog Details</a></li>
                                </ul>
                            </li> -->
                            <li><a href="{% url 'home:department' %}">Department</a></li>
                            
                            <li ><a href="{% url 'patient:appoiment' id=2 %}">Appointment</a></li>

                            <li><a href="{% url 'home:about' %}">About</a></li>
                            <!-- <li><a href="{% url 'home:contact' %}">Contact</a></li> -->
                        </ul>
                    </nav>
                </div>
                {% if request.user.is_authenticated %}
                <div class="col-lg-3">     
                    <div class="header__right">   
                    <ul class="header__right__widget">
                        <li><a href="{% url 'home:signin' %}"><i class="fa fa-home"></i></a></li>  
                        <li><a href="{% url 'home:cart' %}"><i class="fa fa-shopping-cart"></i></a></li>
                        <li><a href="{% url 'home:lout' %}"><i class="fa fa-user-times"></i></a></li>
                    </ul>
                   </div> 
                </div>    
            {% else %}
               <div class="col-lg-3"> 
                <div class="header__right">   
                    <ul class="header__right__widget">
                        <li><a href="{% url 'patient:Pat_signup' %}">Register</a></li>   
                        <li><a href="{% url 'home:signin' %}">Sign-in</a></li>
                    </ul>
                </div>    
                </div>
            {% endif %} 
                </div>
            </div>
            <!-- <div class="canvas__open">
                <i class="fa fa-bars"></i>
            </div> -->
        </div>
    </header>
    <!-- Header Section End -->
        {% block 'content'%}

        {% endblock%}
    

    <!-- Footer Section Begin -->
    <footer class="footer shadow-lg p-3 mt-5 bg-body rounded">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-7">
                    <div class="footer__about">
                        <div class="footer__logo">
                            <!-- <a href="./index.html"><img src="img/logo.png" alt=""></a> -->
                        </div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                        cilisis.</p>
                        <div class="footer__payment">
                            <!-- <a href="#"><img src="img/payment/payment-1.png" alt=""></a> -->
                            <!-- <a href="#"><img src="img/payment/payment-2.png" alt=""></a> -->
                            <!-- <a href="#"><img src="img/payment/payment-3.png" alt=""></a> -->
                            <!-- <a href="#"><img src="img/payment/payment-4.png" alt=""></a> -->
                            <!-- <a href="#"><img src="img/payment/payment-5.png" alt=""></a> -->
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-5">
                    <div class="footer__widget">
                        <h6>Quick links</h6>
                        <ul>
                            <li><a href="#">About</a></li>
                            <li><a href="#">Blogs</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">FAQ</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-4">
                    <div class="footer__widget">
                        <h6>Account</h6>
                        <ul>
                            <li><a href="#">My Account</a></li>
                            <li><a href="#">Orders Tracking</a></li>
                            <li><a href="#">Checkout</a></li>
                            <li><a href="#">Wishlist</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-8 col-sm-8">
                    <div class="footer__newslatter">
                        <h6>NEWSLETTER</h6>
                        <form action="#">
                            <input type="text" placeholder="Email">
                            <button type="submit" class="site-btn">Subscribe</button>
                        </form>
                        <div class="footer__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-youtube-play"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    <div class="footer__copyright__text">
                        <p>Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
                    </div>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search End -->

    <!-- Js Plugins -->
    <script src="{% static 'Prod/js/Pd_jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'Prod/js/Pd_bootstrap.min.js' %}"></script>
    <script src="{% static 'Prod/js/Pd_jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'Prod/js/Pd_jquery-ui.min.js' %}"></script>
    <script src="{% static 'Prod/js/Pd_mixitup.min.js' %}"></script>
    <script src="{% static 'Prod/js/Pd_jquery.countdown.min.js' %}"></script>
    <script src="{% static 'Prod/js/Pd_jquery.slicknav.js' %}"></script>
    <script src="{% static 'Prod/js/Pd_owl.carousel.min.js' %}"></script>
    <script src="{% static 'Prod/js/Pd_jquery.nicescroll.min.js' %}"></script>
    <script src="{% static 'Prod/js/Pd_main.js' %}"></script>
</body>

</html>

home/templates/login.html
<html >
<head>
	{% load static %}
    <meta charset="UTF-8">
    <meta name="description" >
    <meta name="keywords" content="Ashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<style>
	body{
	    background-image: url("{%static 'log\assets\images\bg-themes\2.png' %}");
 		background-size: cover; 
  		background-repeat: no-repeat;
      }
</style>
</head>
       
<body>
	<div class="container d-flex  justify-content-center align-items-center h-100 w-100"
	s>
		{% if messages %}
			{% for message in messages %}
			<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/alertifyjs/build/css/alertify.min.css" />
			<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/alertifyjs/build/css/themes/default.min.css" />
			<script src="https://cdn.jsdelivr.net/npm/alertifyjs/build/alertify.min.js"></script>  
				<script>
					alertify.set('notifier', 'position', 'top-center', 'modalClass', 'my-modal-class');
					alertify.success('{{message}}');
				</script>
			{% endfor %}
		{% endif %}

	  <div class="card  px-5 py-5" style="width: 30%; background-color:rgb(255, 255, 255,0.1);">
		<div class="card-title ">
			<div class="d-flex justify-content-center align-items-center ">
				<a href="{% url 'home:home' %}"><img src="{% static 'assets/img/logo/logo.png' %}" alt=""></a>		 
			</div>
		</div>
		<div class="card-body p-0 ">
			<h4 class="text-center text-uppercase">Sign in</h4>
			<form action="{% url 'home:signin' %}" method="post">
				{% csrf_token %}
				<div class="mb-2">
					<label for="" class="form-label">Username  </label>
					<input type="text" name="username" id="" class="form-control" 
					style="background-color: transparent;border-color:rgb(255, 255, 255,0.3)">
				</div>
				<div class="mb-2">
					<label for="" class="form-label">Password  </label>
					<input type="password" name="password" id="" class="form-control"
					 style="background-color: transparent; border-color:rgb(255, 255, 255,0.3)">
				</div>
				<div class="d-flex justify-content-center">
					<button class="btn btn-md w-50" 
					style="background-color: rgb(77, 78, 79,0.3); color: whitesmoke;" type="submit">Submit</button>
				</div>
			</form>
			<a href="{% url 'home:forgotP' %}" style="text-decoration: none; color: black;">Forgot Password</a>

		</div>
	  </div>	
    </div>
   </body>   
</html>            