admn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from admn import views 

urlpatterns = [
    # path('patient/', include(('patient.urls', 'patient'), namespace='patient')),
    path('ad_Product',views.ad_Product,name='ad_Product'),
    path('ad_varient/<int:id>',views.ad_varient,name='ad_varient'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('show_Product',views.show_Product,name='show_Product'),
    path('delete',views.delete_item,name='delete-item'),
    path('block',views.block,name='block'),
    path('unblock',views.unblock,name='unblock'),
    path('show_users',views.show_users,name='show_users'),
    path('show_doct',views.show_doct,name='show_doct'),
    path('delet_varit/<int:id>',views.delet_varit,name='delet_varit'),
    path('del_va/<int:id>',views.del_va,name='del_va'),
    path('edit_prod/<int:id>',views.edit_prod,name='edit_prod'),
    path('pat_up',views.pat_up,name='pat_up'),
    path('delet_users',views.delet_users,name='delet_users'),
    path('doc_up',views.doc_up,name='doc_up'),
    path('catagory',views.catagory,name='catagory'),
    path('catagory_delet/<int:id>',views.catagory_delet,name='catagory_delet'),
    path('catagory_edit/<int:id>',views.catagory_edit,name='catagory_edit'),
    path('add_catagory',views.add_catagory,name='add_catagory'),
    path('medicine_type',views.medicine_type,name='medicine_type'),
    path('add_medicine_type',views.add_medicine_type,name='add_medicine_type'),
    path('medicine_delet',views.medicine_delet,name='medicine_delet'),
    path('medicine_type_edit/<int:id>',views.medicine_type_edit,name='medicine_type_edit'),
    path('search',views.search,name='search'),
    path('month',views.monthly_sales_report,name='month'),
    path('day',views.daily_sales_report,name='day'),
    path('today',views.today_report,name='today'),
    path('week',views.weekly_report,name='week'),
    path('year',views.yearly_report,name='year'),
    path('download',views.download,name='download'),
    path('admin_order',views.admin_order,name='admin_order'),
    path('admin_order_refund',views.admin_order_refund,name='admin_order_refund'),
    path('admin_order_specific',views.admin_order_specific,name='admin_order_specific'),
    path('admin_c',views.admin_ord_c,name='admin_c'),
    path('get_subcategories/', views.get_subcategories, name='get_subcategories'),
    path('orderstatus',views.orderstatus,name='orderstatus'),
    path('refundstatus',views.refundstatus,name='refundstatus'),
    path('order_summery<int:id>',views.order_summery,name='order_summery'),
    path('coupn',views.coupn,name='coupn'),
    path('coupnedit/<int:id>',views.coupnedit,name='coupnedit'),
    path('coupndelete',views.coupndelete,name='coupndelete'),
    path('coupnshow',views.coupnshow,name='coupnshow'),
    path('sales_search',views.sales_search,name='sales_search'),
    path('department',views.department_show,name='department'),
    path('department_add',views.department_add,name='department_add'),
    path('department_edit/<int:id>',views.department_edit,name='department_edit'),
    path('department_delete',views.department_delete,name='department_delete'),







]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docter/urls.py
app_name='docter'

from django.contrib import admin
from django.urls import path,include
from docter import views

urlpatterns = [

 path('doc_dashboard',views.doc_dashboard,name='doc_dashboard'),
 path('doc_appointment',views.doc_appointment,name='doc_appointment'),
 path('today_appointment',views.today_appointment,name='today_appointment'),
 path('update_is_available',views.update_is_available,name='update_is_available'),
 path('docno',views.doc_Product,name='docno'),
 path('doc_Profile',views.doc_profile,name='doc_Profile'),
 path('doc_edit_profile',views.doc_edit_profile,name='doc_edit_profile'),
 path('appointment_status/<int:id>/<str:keyword>',views.appointment_status,name='appointment_status'),
 path('priscribe/<int:id>',views.prescribe,name='prescribe'),
 path('myPatient',views.myPatient,name='myPatient'),
 path('today_Patient',views.today_Patient,name='today_Patient'),
 path('doc_chat',views.doc_chat,name='doc_chat'),
 path('doc_Password',views.doc_Password,name='doc_Password'),
#  path('incr/<int:id>',views.incr,name='incr'),
#  path('pre2/<int:id>',views.pre2,name='pre2'),
 path('changeTime',views.changeTime,name='changeTime'),
 path('exam',views.exam,name='exam'),

 







 
]

home/urls.py
app_name='home'

from django.contrib import admin
from django.urls import path,include
from home import views

urlpatterns = [
    # path('adm/',include('admn.urls')),
    path('',views.home,name='home'),
    path('contact',views.contact,name='contact'),
    path('about',views.about,name='about'),
    path('docter',views.docter,name='docter'),
    path('department',views.department,name='department'),
    path('signin',views.signin,name='signin'),
    path('lout', views.lout, name='lout'),
    path('item/',views.item,name='item'),
    path('medicine/<str:med>',views.medicine,name='medicine'),
    # path('tablet',views.tablet,name='tablet'),
    # path('capsule',views.capsule,name='capsule'),
    # path('syrup',views.syrup,name='syrup'),
    # path('oiment',views.oiment,name='oiment'),
    # path('powder',views.powder,name='powder'),
    # path('gel',views.gel,name='gel'),
    path('checkout',views.checkout,name='checkout'),
    path('order/<int:item>',views.order,name='order'),
    path('cart',views.cart,name='cart'),
    path('decr/<int:id>',views.decr,name='decr'),
    path('incr/<int:id>',views.incr,name='incr'),
    path('delet_cartItem/<int:id>',views.delet_cartItem,name='delet_cartItem'),
    path('add_cart/<int:id>',views.add_cart,name='add_cart'),
    path('product_page/<int:id>',views.product_page,name='product_page'),
    path('forgotP/',views.forgetP,name='forgotP'),
    path('changeP/<str:token>',views.changeP,name='changeP'),
    path("index", views.index, name="index"),
    path('adres',views.adres,name='adres'),
    path('remark/<int:id>',views.edit_address,name='remark'),
    path('delete_address',views.delete_address,name='delete_address'),
    path('coupon',views.coup,name='coupon'),
    path('delet_session',views.delete_session,name='delet_session'),
    path('high/<str:item>', views.high, name='high'),
    path('low/<str:item>', views.low, name='low'),
    path('success/',views.success,name='success'),
    path('verify_otp',views.verify_otp,name='verify_otp'),
    path('verify_email/<str:id>',views.verify_email,name='verify_email'),
    path('payment_cancel/<int:id>',views.payment_cancel,name='payment_cancel'),
    path('verification',views.verification,name='verification'),
    
    # path('hat',views.message,name='hat'),
     
]

hosp_mng/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('adm/',include('admn.urls')),
    path('Patient/',include('patient.urls')),
    path('docter/',include('docter.urls')),
    path('',include('home.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

docter/forms.py
from .models import DoctorProfile,Department
from django import forms
from django.forms import ModelForm

class doc_form(forms.ModelForm):
    class Meta:
        model=DoctorProfile
        exclude=['user','email_verify','is_verify','is_available','consult_start','consult_end']


class department_form(forms.ModelForm):
    class Meta:
        model=Department
        fields='__all__'        

docter/views.py
from django.shortcuts import render,redirect,HttpResponse
from .models import DoctorProfile
from django.db.models import Prefetch
from admn.models import Product,varient
from home.models import Appointment,treatment,TreatMedicine,User
from .forms import doc_form
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta,time
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Case, When, Value, IntegerField
from django.views.decorators.cache import cache_control
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.contrib import messages


# Create your views here.



@login_required(login_url='home:signin')
def doc_dashboard(request):
    if request.user.is_authenticated:
        if request.user.is_docter:
            Pr_no=Product.objects.count()
            My_no=Appointment.objects.filter(docter__user_id=request.user.id , status='finish').count()
            P_no=Appointment.objects.filter( status='finish').count()
            AP_no=Appointment.objects.filter(docter__user_id=request.user.id ).count()
            
            docter=DoctorProfile.objects.get(user_id=request.user.id)
            # print(docter.image,docter.badge_id)
            if docter is None:
                print('iam in docter')
                docter=DoctorProfile(user_id=request.user.id)
                docter.save()
                docter=DoctorProfile.objects.filter(user_id=request.user.id)
                context={'docter':docter,'Pr_no':Pr_no,'My_no':My_no,'P_no':P_no,'AP_no':AP_no ,'page':'dash'}
                return render(request,'doc_home.html',context)
            
            if docter.image !=None and docter.badge_id !=None:
                print('iam home doc') 
                context={'docter':docter,'Pr_no':Pr_no,'My_no':My_no,'P_no':P_no,'AP_no':AP_no,'page':'dash'}
                return render(request,'doc_home.html',context)
            
            if docter.image == None or docter.badge_id == None:
                print('iam home doc') 
                context={'docter':docter,'Pr_no':Pr_no,'My_no':My_no,'P_no':P_no,'AP_no':AP_no,'page':'dash'}
                return render(request,'doc_home.html',context)
            
            context={'docter':docter,'Pr_no':Pr_no,'My_no':My_no,'P_no':P_no,'AP_no':AP_no,'page':'dash'}
            return render(request,'doc.html',context)
             
        return redirect('signin')      
       
    return redirect('signin')      

@login_required(login_url='home:signin')
def exam(request):
    return render(request,'HospitalDocter.html')

@login_required(login_url='home:signin')
def doc_profile(request):
    if request.method=='POST':
        form=doc_form(request.POST , request.FILES)
        # print('halo')
        if form.is_valid():
            # print('halo')
            docter=DoctorProfile.objects.get(user_id=request.user.id)
            if docter:
                docter.specialization=form.instance.specialization
                docter.gender=form.instance.gender
                docter.image=form.instance.image
                docter.department=form.instance.department
                docter.address=form.instance.address
                docter.residence=form.instance.residence
                docter.contact_number='+91'+form.instance.contact_number
                docter.badge_id=form.instance.badge_id
                docter.save()
                return redirect('docter:doc_dashboard')
            else:
                return redirect('docter:doc_dashboard')
        else:
            print('else woe')    
            return redirect('docter:doc_dashboard')    
          

    else:
        docter=DoctorProfile.objects.get(user_id=request.user.id)
        form=doc_form()
        return render(request,'doc_profile.html',{'form':form,'docter':docter,'page':'dash'})

@login_required(login_url='home:signin')
def doc_edit_profile(request):
    if request.method=='POST':
        form=doc_form(request.POST , request.FILES)
        # print('halo')
        if form.is_valid():
            # print('halo')
            try:
                docter=DoctorProfile.objects.get(user_id=request.user.id)
            except:               
               return render(request,'doc_home.html')
                     
            if docter:
                docter.specialization=form.instance.specialization
                docter.gender=form.instance.gender
                docter.image=form.instance.image
                docter.department=form.instance.department
                docter.address=form.instance.address
                docter.residence=form.instance.residence
                docter.contact=form.instance.contact
                docter.badge_id=form.instance.badge_id
                docter.save()
                return redirect('docter:doc_dashboard')
                
        else:
            return redirect('docter:doc_dashboard')
            

    else:
        profile=DoctorProfile.objects.get(user_id=request.user.id)
        form=doc_form(instance=profile)
        return render(request,'doc_profile.html',{'form':form,'docter':profile,'page':'dash'})    
    
@login_required(login_url='home:signin')
def doc_Product(request):
      
      product=Product.objects.prefetch_related(Prefetch('item',queryset=varient.objects.all()))
      docter=DoctorProfile.objects.get(user_id=request.user.id)
      print(docter)
      context={'product':product,'docter':docter,'page':'medicine'} 
      return render(request,'doc_Product.html',context)


def doc_time_options():
    times = []
    for hour in range(0, 24):
        for minute in range(0, 60, 15):  
            time_obj = time(hour, minute)
            time_str = time_obj.strftime('%H:%M')
            times.append((time_str, time_str))
    return times



@login_required(login_url='home:signin')
def doc_appointment(request):
    today=datetime.now().date()
    doct=DoctorProfile.objects.get(user=request.user)
    print(doct.id)
    Patient_list=Appointment.objects.filter(docter_id=doct.id).order_by(
        Case(
        When(appointment_date__gt=today, then=Value(2)),
        When(appointment_date=today, then=Value(1)),
        default=Value(3),
        output_field=IntegerField(),
    ),
    Case(
        When(status='pending', then=Value(1)),
        When(status='accept', then=Value(2)),
        When(status='reject', then=Value(3)),
        When(status='finish', then=Value(4)),
        default=Value(5),
        output_field=IntegerField(),
    ),
        'appointment_date')
    print(Patient_list)
    docter=DoctorProfile.objects.get(user_id=request.user.id)
    context={'Appointment':Patient_list,'docter':docter,'page':'appoiment'}
    return render(request,'doc_appointment.html',context)

@login_required(login_url='home:signin')
def changeTime(request):
    if request.method == 'POST':
        start=request.POST.get('start_time')
        end=request.POST.get('end_time')
        start_time = datetime.strptime(start, "%H:%M").time()
        end_time = datetime.strptime(end, "%H:%M").time()
        doc = DoctorProfile.objects.get(user=request.user)
        doc.consult_start = start_time
        doc.consult_end = end_time
        doc.save()
        return redirect('docter:doc_appointment')
    else:
        docter = DoctorProfile.objects.get(user=request.user)
        time_options =doc_time_options()
        context={'docter':docter,'start':time_options,'end':time_options,'page':'time'}
        return render(request,'doc_time.html',context)
        
@login_required(login_url='home:signin')
@csrf_exempt
def update_is_available(request):
    if request.method=='POST':
        id=request.POST.get('item_id')
        is_available=request.POST.get('is_available')
        docter=DoctorProfile.objects.get(id=id)
        print(is_available)
        if is_available =='true':
            print("true")
            docter.is_available = True
            docter.save()
        else:
            print("false")
            docter.is_available = False
            docter.save()    
        return JsonResponse({'is_available': docter.is_available})
    
    else:
        return JsonResponse({'error': 'Invalid request method.'})



@login_required(login_url='home:signin')
def today_appointment(request):
    today=datetime.now().date()
    doct=DoctorProfile.objects.get(user=request.user)
    Patient_list=Appointment.objects.filter(docter_id=doct.id,appointment_date=today).order_by('appointment_time')
    docter=DoctorProfile.objects.filter(user_id=request.user.id)
    context={'Appointment':Patient_list,'docter':doct,'today':today,'page':'appoiment'}
    return render(request,'doc_appointment.html',context)


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='home:signin')
def appointment_status(request,id,keyword):
    print(keyword)
    try:
       appoiment=Appointment.objects.get(id=id)
       if appoiment.status != 'finish':
            if keyword == 'finish':
                id=appoiment.id
                return redirect('docter:prescribe',id)
            appoiment.status=keyword
            appoiment.save() 
            return redirect('docter:doc_appointment')
       return redirect('docter:doc_appointment')
    except:
       return redirect('docter:doc_appointment')


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='home:signin')    
def prescribe(request,id):
    id=id
    if request.method=='POST':
        symtems= request.POST['symtems']
        selected_items = request.POST.getlist('selected_items[]')
        quantity = request.POST.getlist('quantities[]')
        tret = treatment(appointment_id=id, symtems=symtems)
        tret.save()
        for i in range(len(selected_items)):

docter/templates/doc.html
<!DOCTYPE html>
<html lang="en">

    <head>
      {%load static%}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>Dashboard-Docter</title>
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
        <link rel="stylesheet"  href="{%static 'Doc\css\HospitalDocter.css' %}">
        {% block js %}
        {% endblock %}
        <style>
          @keyframes vibrationCall {
          0%  {transform: rotate(0deg);}
          25% {transform: rotate(3deg);}
          50% {transform: rotate(0deg);}
          75% {transform: rotate(-3deg);}
          100% {transform: rotate(0deg);}
          
        }
          #vedioAnswercall{
            width: 100%;
            height: 100%;
            position: absolute;
            background-color: rgb(83, 83, 84,0.5);
            z-index: 9999998;
            display: none;          
          }
         .answerBox{
          width: 300px;
          height: 100px;
          position: absolute;
          top: 50%;
          left: 50%;
          transform: translate(-50%,-50%);
          background-color: white;
          z-index: 9999999;
          display: flex;
          justify-content:center;
          align-items: center;
          flex-direction: column;
          gap: 5px;
          border-radius: 5px;
          animation: vibrationCall 1ms linear 0s infinite ;


         }

          .video-box {
                      position: absolute;
                      display: none;
                      right: 10%;
                      top:10%;
                      width: 500px;
                      height: auto;
                      /* cursor: move; */
                      z-index: 99990;
                      border-radius: 10px;
                      resize: both;
                      overflow:auto;
                      background-color: rgb(255, 255, 255,0.5);
                  }
           #closeButton{
             cursor:pointer;
             position: absolute;
             bottom: 2%;
             right: 40%;
             color: red;
             z-index: 99999;
             padding: 5px 10px 5px 10px;
             border-radius: 50%;
             background-color: aliceblue;
           }       
           #stopvedioButton{
            cursor:pointer;
            position: absolute;
            bottom: 2%;
            right: 50%;
            z-index: 99999;
            padding: 5px 10px 5px 10px;
             border-radius: 50%;
             background-color: aliceblue;
           }

           #video-box-User{
            position: absolute;
                      display: none;
                      right: 1%;
                      bottom:1%;
                      width: 100px;
                      height: auto;
                      cursor: move;
                      z-index: 99999;
                      border-radius: 10px;
                      /* resize: both; */
                      overflow:auto;
                      background-color: rgb(255, 255, 255,0.5);
           }
          @media (max-width:578px) {
      
           .video-box{
               width: 350px;
               height: 350px;
            }
            .answerBox{
              position: absolute;
              top: 50%;
              left: 10%;
              transform: translate(-50%,-50%);
            }
      
          }
        </style>   
    </head>
      <body>
        <div id="vedioAnswercall">
            <div class="answerBox">
              <p>Patient<label id="callerPerson"></label> is  calling...</p>
              <div>
                <button type="button" class="btn btn-success" id="callAnswer">Answer</button>
                <button type="button" class="btn btn-danger" id="callDecline">Decline</button> 
              </div>
              <audio id="caller"  style="position: absolute; bottom: 0 ; 
                          left: 0;   visibility: hidden;"  loop>
                <source src="{%static 'log\assets\audio\simple_bell_2.mp3'%}" type="audio/mp3">
              </audio> 
            </div> 
        </div>
        <div class="Patienthead px-3">
         <div>
          <a href="{% url 'home:home' %}"id="adminimage">
            <img src="{%static 'Doc\img\loder.png'%}" alt="" width="100%" height="100%" class="adminimg2">
            <img src="{%static 'Doc\img\logo.png'%}" alt="" width="100%" height="100%" class="adminimg1">
          </a>
         </div> 
         <div class="Right">
           <form class="headsearch"role="search">
              <input class="form-control mx-1 " type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-sm btn-success headsearchbtn" type="submit">Search</button>
           </form>
           <a href="{% url 'home:lout' %}" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-title="LogOut" >
              <i class="bi bi-person-square"></i>
           </a>
           <!-- <i class="bi bi-person-down border  border-4 border-info-subtle rounded-circle px-2"></i> -->
           <a href="javascript:void(0)" id="headerarrow" onclick="openNav()"><i class="fas  fa-align-justify"
             style="font-size:20px; border: 5px solid; border-radius:5px;padding: 3px 5px 3px 5px; margin-top: 5px;"></i></a> 
          </div>
        </div>
        <div class="adminbody">
          <div class="video-box" id="video-Box">
            <!-- Video chat elements will go here -->
                <i class="bi bi-telephone-fill" id="closeButton"></i>
                <i class="bi bi-camera-video-off-fill" id="stopvedioButton"></i>
                <div class="video-box-user" id="video-box-User"></div>
  
          </div>
          <div id="mySidenav" class="sidenav" >
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <form class="mt-3 my-2 searchNavigation"role="search">
              <input class="form-control mx-1 " type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-sm btn-success searchNavigationbtn" type="submit">Search</button>
           </form>
           <li class="sidebar-header">MAIN NAVIGATION</li>
             
            <ul class="m-0 p-0">
              <li class="nav-link {%if page == 'dash' %} active {%endif%}">
                <a href="{% url 'docter:doc_dashboard'%}" class="mx-4">
                  <i class="bi bi-houses me-2"></i><span>Dashboard</span>
                </a>
              </li>
              <li class="nav-link {%if page == 'appoiment' %} active bg-transBody{%endif%}">
                <a href="{% url 'docter:doc_appointment' %}" class="mx-4 {%if page == 'appoiment' %}text-dark{%endif%}">
                  <i class="bi bi-slack me-2"></i><span>Appointent List</span>
                </a>
              </li>
              <li class="nav-link {%if page == 'medicine' %} active bg-transBody{%endif%}">
                <a href="{% url 'docter:docno' %}" class="mx-4 {%if page == 'medicine' %} text-dark{%endif%}">
                  <i class="bi bi-slack me-2"></i><span>Medicine List</span>
                </a>
              </li>
               
              <li class="nav-link {%if page == 'Patient' %} active bg-transBody{%endif%}">
                <a href="{% url 'docter:myPatient'%}" class="mx-4 {%if page == 'Patient' %} text-dark{%endif%}"> 
                  <i class="bi bi-slack me-2"></i><span>Patient List</span>
                </a>
              </li>
              <li class="nav-link {%if page == 'time' %} active bg-transBody{%endif%}">
                <a href="{% url 'docter:changeTime'%}" class="mx-4{%if page == 'time' %} text-dark{%endif%}"> 
                  <i class="bi bi-slack me-2"></i><span>Consult Time</span>
                </a>
              </li>
              <li class="nav-link {%if page == 'chat' %} active bg-transBody{%endif%}">
                <a href="{% url 'docter:doc_chat'%}" class="mx-4{%if page == 'chat' %} text-dark{%endif%}"> 
                  <i class="bi bi-slack me-2"></i><span>Chat</span>
                </a>
              </li>
              <li class="nav-link {%if page == 'password' %} active bg-transBody{%endif%}">
                <a href="{% url 'docter:doc_Password'%}" class="mx-4 {%if page == 'password' %} text-dark{%endif%}"> 
                  <i class="bi bi-slack me-2"></i><span>Password Change</span>
                </a>
              </li>

            </ul>
            <ul style="position: absolute; bottom:10% ; left:0%;">
              <div class="form-check form-switch d-flex flex-column">
                <label class="form-check-label" for="flexSwitchCheckDefault">Available</label>
                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" 
                       data-id="{{ docter_id }}" {% if docter_available %}checked{% endif %}>
              </div> 
            </ul>
            <div class="menufooter">
              <div class="sidenav-footer">
                <div class="d-flex">
                  <div class="col-8">
                    <div class="small">Logged in as:</div>
                    {{request.user.username}}
                  </div>
                  <div class="col-4 d-flex justify-content-end">
                    {%if profile_picture_url%}
                      <img src="{{ profile_picture_url.url }}" class="img-radius w-50 h-100 rounded-circle" alt="User-Profile-Image">
                    {%else%}
                    <img src=""  alt="User" class="img-radius w-50 h-100 rounded-circle"
                    onerror="this.src='{% static 'chat/img/unknown.jpg' %}';">
                    {%endif%}
                  </div>
                </div>
              </div> 
            </div>
            <script  src="{%static 'Doc\js\HospitalDocter.js' %}"></script>
            <script  src="{%static 'Doc\js\available.js' %}"></script> 
          </div>  
          <div class="admincontent">
                    {% if messages%}                  
                       {% for message in messages %}
                          {% if message.tags == 'error'%}
                              <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
                              <script>
                                  var m="{{message}}";
                                  console.log(m);
                                  Swal.fire({
                                          position: 'center',
                                          icon: 'error',
                                          title: m,
                                          showConfirmButton: false,
                                          timer: 4000
                                          })
                                </script>
                          {%endif%}
                          {% if message.tags == 'success'%}
                                <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
                                <script>
                                    var m="{{message}}";
                                    console.log(m);
                                    Swal.fire({
                                            position: 'center',
                                            icon: 'success',
                                            title: m,
                                            showConfirmButton: false,
                                            timer: 4500
                                            })
                                    </script>
                          {%endif%}       
                        {% endfor %}
                    {%endif%}
                {%if profile_verfy_check%}
                    {% block 'content' %}
                   
                    {% endblock %} 
                   
                {%else%}          
                  <div class="d-flex justify-content-center align-items-center mt-5">
                     <h4>
                       verify your phone number <a href="{% url 'home:verification' %}" class="text-dark"><strong>Click hear</strong></a>
                     </h4>
                  </div>
                {%endif%}          
          </div>
                 
      </body>
</html>

docter/templates/doc_Password.html
{% extends "doc.html" %}
{% load static%}
{% block 'content' %}
<div class="w-100 h-100">
   <div class="row d-flex justify-content-center align-items-center w-100 h-100">
    <div class="card col-lg-5 col-sm-10 p-5 bg-transBody">
      <div class="text-center mb-4"><h4>Change Password</h4></div>
      <form action="{% url 'docter:doc_Password' %}" method="post">
        {% csrf_token %}
        <div class="form-floating mb-3">
            <input class="form-control" id="inputEmail" type="text"  name="passw" placeholder="Password" />
            <label for="inputEmail" >Password</label>
        </div>
        <div class="form-floating mb-3">
            <input class="form-control" id="inputPassword" type="password" name="con_passw" placeholder="Password" />
            <label for="inputPassword">Conform Password</label>
        </div>
        <div class="text-center mt-4 mb-0">
            <button class="btn btn-success w-50" type="submit">submit</button>
        </div>
      </form>
   </div>
   </div>
</div>
{%endblock%}