admn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from admn import views 

urlpatterns = [
    # path('patient/', include(('patient.urls', 'patient'), namespace='patient')),
    path('ad_Product',views.ad_Product,name='ad_Product'),
    path('ad_varient/<int:id>',views.ad_varient,name='ad_varient'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('show_Product',views.show_Product,name='show_Product'),
    path('delete',views.delete_item,name='delete-item'),
    path('block',views.block,name='block'),
    path('unblock',views.unblock,name='unblock'),
    path('show_users',views.show_users,name='show_users'),
    path('show_doct',views.show_doct,name='show_doct'),
    path('delet_varit/<int:id>',views.delet_varit,name='delet_varit'),
    path('del_va/<int:id>',views.del_va,name='del_va'),
    path('edit_prod/<int:id>',views.edit_prod,name='edit_prod'),
    path('pat_up',views.pat_up,name='pat_up'),
    path('delet_users',views.delet_users,name='delet_users'),
    path('doc_up',views.doc_up,name='doc_up'),
    path('catagory',views.catagory,name='catagory'),
    path('catagory_delet/<int:id>',views.catagory_delet,name='catagory_delet'),
    path('catagory_edit/<int:id>',views.catagory_edit,name='catagory_edit'),
    path('add_catagory',views.add_catagory,name='add_catagory'),
    path('medicine_type',views.medicine_type,name='medicine_type'),
    path('add_medicine_type',views.add_medicine_type,name='add_medicine_type'),
    path('medicine_delet',views.medicine_delet,name='medicine_delet'),
    path('medicine_type_edit/<int:id>',views.medicine_type_edit,name='medicine_type_edit'),
    path('search',views.search,name='search'),
    path('month',views.monthly_sales_report,name='month'),
    path('day',views.daily_sales_report,name='day'),
    path('today',views.today_report,name='today'),
    path('week',views.weekly_report,name='week'),
    path('year',views.yearly_report,name='year'),
    path('download',views.download,name='download'),
    path('admin_order',views.admin_order,name='admin_order'),
    path('admin_order_refund',views.admin_order_refund,name='admin_order_refund'),
    path('admin_order_specific',views.admin_order_specific,name='admin_order_specific'),
    path('admin_c',views.admin_ord_c,name='admin_c'),
    path('get_subcategories/', views.get_subcategories, name='get_subcategories'),
    path('orderstatus',views.orderstatus,name='orderstatus'),
    path('refundstatus',views.refundstatus,name='refundstatus'),
    path('order_summery<int:id>',views.order_summery,name='order_summery'),
    path('coupn',views.coupn,name='coupn'),
    path('coupnedit/<int:id>',views.coupnedit,name='coupnedit'),
    path('coupndelete',views.coupndelete,name='coupndelete'),
    path('coupnshow',views.coupnshow,name='coupnshow'),
    path('sales_search',views.sales_search,name='sales_search'),
    path('department',views.department_show,name='department'),
    path('department_add',views.department_add,name='department_add'),
    path('department_edit/<int:id>',views.department_edit,name='department_edit'),
    path('department_delete',views.department_delete,name='department_delete'),







]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hosp_mng/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('adm/',include('admn.urls')),
    path('Patient/',include('patient.urls')),
    path('docter/',include('docter.urls')),
    path('',include('home.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

patient/urls.py
app_name='patient'

from django.contrib import admin
from django.urls import path,include
from patient import views

urlpatterns = [
    # path('adm/',include('admn.urls')),
    path('Pat_signup',views.Pat_signup,name='Pat_signup'),
    path('Pat_dashboard',views.Pat_dashboard,name='Pat_dashboard'),
    path('appoiment/<int:id>',views.appoiment,name='appoiment'),
    path('Patient_appoiment',views.Patient_appointment,name='Patient_appoiment'),
    path('treatment',views.treat,name='treatment'),
    path('get_available_time_slots/', views.get_available_time_slots, name='get_available_time_slots'),
    path('pat_chat',views.pat_chat,name='pat_chat'),
    path('adres/<int:id>',views.adres,name='adres'),
    path('edit_adres/<int:id>/<int:item>',views.edit_adres,name='edit_adres'),
    path('delete_adres/<int:id>/<int:item>',views.delete_adres,name='delete_adres'),
    path('check/<int:id>',views.check,name='check'),
    path('copn/<int:id>',views.copn,name='copn'),
    path('d_order/<int:id>',views.d_order,name='d_order'),
    path('invoice/<int:id>',views.invoice,name='invoice'),
    path('ord',views.ord,name='ord'),
    path('ord_hys',views.ord_hys,name='ord_hys'),
    path('cancel_order',views.cancel_order,name='cancel_order'),
    path('refund/<int:id>',views.refund,name='refund'),
    path('p_profile',views.p_profile,name='p_profile'),
    path('ord_success/',views.ord_success,name='ord_success'),
    path('pay_cancel/<int:id>/<int:item>',views.pay_cancel,name='pay_cancel'),
    path('delet_coupen/<int:id>',views.delete_coupen,name='delet_coupen'),
    path('exam',views.exam,name='exam'),

   







    

]

home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,User
from django.db.models.signals import post_save
from django.dispatch import receiver
from docter.models import DoctorProfile
from patient.models import patientProfile,Address
from django.conf import settings
from admn.models import Product,varient,coupen 
from asgiref.sync import sync_to_async
  


user=settings.AUTH_USER_MODEL

class User(AbstractUser):
    is_patient=models.BooleanField(default=False)
    is_docter=models.BooleanField(default=False)
    block=models.BooleanField(default=False)
    online=models.BooleanField(default=False)
    f_passw=models.CharField(max_length=1000,null=True,blank=True)
    
    

class Cart(models.Model):
    user=models.OneToOneField(User,on_delete=models.SET_NULL ,null=True)
    created= models.DateTimeField(auto_now_add=True)
    
     
class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name='cart_items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE,null=True)
    Varient=models.ForeignKey(varient,on_delete=models.CASCADE,null=True)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(default=0,max_digits=10, decimal_places=2)
    
    def __str__(self):
         return str(self.product)

class Order(models.Model):
    data=(
          ('pending','pending'),
          ('shiped','shiped'),
          ('deliverd','deliverd'),
          ('cancel','cancel'),
          ('revoke','revoke')
     )
    user=models.ForeignKey(User,on_delete=models.SET_NULL ,null=True)
    Total_Price = models.DecimalField(default=0,max_digits=10, decimal_places=2)
    address=models.ForeignKey(Address,on_delete=models.CASCADE,null=True)
    Pay_option=models.CharField(max_length=10,null=True)
    order_date= models.DateTimeField(auto_now_add=True)
    delivery_date= models.DateTimeField(blank=True,null=True)
    cancel_date= models.DateTimeField(blank=True,null=True)
    status=models.CharField(max_length=10,choices=data,default="pending",null=True,blank=True) 
    discount=models.ForeignKey(coupen,on_delete=models.SET_NULL,null=True) 
    razor_payid=models.CharField(max_length=200,null=True,blank=True)
    razor_orderid=models.CharField(max_length=200,null=True,blank=True) 
    razor_signature=models.CharField(max_length=200,null=True,blank=True) 
        

       
    def __str__(self):
         return str(self.user)
    
     
class orderItem(models.Model):
    order = models.ForeignKey(Order, related_name='order_items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE,null=True)
    Varient =models.ForeignKey(varient,on_delete=models.CASCADE,null=True)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(default=0,max_digits=10, decimal_places=2)
    
    def __str__(self):
         return str(self.product)


class Refund(models.Model):
    data=(
          ('pending','pending'),
          ('Process' ,'Process'),
          ('cancel','cancel'),
          ('completed','completed'),
     )
    mony=(
          ('bank','bank'),
          ('wallet','wallet'),
     )
    user=(
          ('admin','admin'),
          ('user','user'),
     )
    order= models.ForeignKey(Order, related_name='order_refund',on_delete=models.CASCADE,null=True,blank=True)
    refund_option=models.CharField(max_length=10,choices=mony,default="wallet",null=True,blank=True) 
    refund_reason=models.CharField(max_length=200,null=True,blank=True)
    status=models.CharField(max_length=10,choices=data,default="pending",null=True,blank=True) 
    cancelby=models.CharField(max_length=100,choices=user,default="none",null=True,blank=True)
    refund_amount=models.PositiveIntegerField(null=True,blank=True)

    def __str__(self):
         return str(self.pk)

class Appointment(models.Model):
     data=(
          ('Pending','Pending'),
          ('accept','accept'),
          ('reject','reject'),
          ('finish','finish'),
     )
     patient=models.ForeignKey(patientProfile,on_delete=models.CASCADE,null=True,blank=True)
     docter=models.ForeignKey(DoctorProfile,on_delete=models.CASCADE,null=True,blank=True)
     appointment_date=models.DateField(null=True,blank=True)
     appointment_time=models.TimeField(null=True,blank=True)
     reason=models.TextField(max_length=500)
     status=models.CharField(max_length=10,choices=data,default="pending",null=True,blank=True)    
     created_at= models.DateTimeField(auto_now_add=True)
      
     def __str__(self):
          # doctor = sync_to_async(lambda: self.doctor)()
          # return str(doctor)
          return str(self.docter)      
 

                                              
class treatment(models.Model):
     appointment=models.ForeignKey(Appointment,on_delete=models.CASCADE,related_name='OP')
     symtems=models.TextField(max_length=500)
     ordstatus=models.BooleanField(default=False)

     def __str__(self):
          return str(self.appointment)   


class TreatMedicine(models.Model):
        Treatment=models.ForeignKey(treatment , on_delete=models.CASCADE,related_name='treat',null=True)
        medicine = models.ForeignKey(varient, on_delete=models.CASCADE,related_name='sup')
        quantity = models.PositiveIntegerField(default=0) 
        
            

patient/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class patientProfile(models.Model):
    choice=(
        ('Male','Male'),
        ('Female','Female')
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='patient_profile')
    contact_number = models.CharField(max_length=15,null=True)
    gender=models.CharField(max_length=100,  choices=choice)
    image=models.ImageField(upload_to='pat')
    is_verify=models.BooleanField(default=False)
    email_verify=models.BooleanField(default=False)
    # address=models.TextField(max_length=200,null=True,blank=True)


    def __str__(self):
        return self.user.username


class wallet(models.Model):
    PatientProfile=models.ForeignKey(patientProfile,on_delete=models.CASCADE,null=True)
    amount=models.PositiveIntegerField(null=True)


class Address(models.Model):
    Patient = models.ForeignKey(patientProfile, on_delete=models.CASCADE, related_name='adres',null=True)
    Name=models.CharField(max_length=30,null=True)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    district = models.CharField(max_length=50,null=True)
    state = models.CharField(max_length=50)
    country=models.CharField(max_length=100,null=True)
    Pin_code = models.CharField(max_length=10)
    contact=models.PositiveIntegerField(null=True)
    email=models.EmailField(null=True,blank=True)
    # def __str__(self):
    #     return self.user.username

patient/forms.py
from .models import Address,patientProfile
from django import forms
from django.forms import ModelForm
from datetime import datetime

class adrs_form(forms.ModelForm):
    class Meta:
        model=Address
        exclude=['Patient']
        

class patient_form(forms.ModelForm):
    class Meta:
        model=patientProfile
        exclude=['user','is_verify','email_verify']
                

patient/templates/Patient_Profile.html
{% extends "user-admin.html" %}
{%load crispy_forms_tags %} 
{% block 'content' %}
<div class="container">
    <div class="row justify-content-center mt-5 ">
        {% if messages %}
             {% for message in messages %}
             <div class="toast align-items-center text-white bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                  <div class="toast-body">
                   {{message}}
                  </div>
                  <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
              </div>
            {% endfor %}
        {%endif%}  
        <div class="card col-lg-5 col-md-9 col-sm-10 p-5">
            <h3 class="text-center">PROFILE</h3>
            <form action="{% url 'patient:p_profile' %}" method="post" enctype="multipart/form-data">
                {%csrf_token%}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary" >Submit</button>
            </form>
        </div>
    </div>
</div>            

{%endblock%}

patient/templates/Patient_Profileverify.html
{% extends "user-admin.html" %}
{%load crispy_forms_tags %} 
{% block 'content' %}
<div class="container">
    <div class="row justify-content-center mt-5 ">
        {% if messages %}
             {% for message in messages %}
             <div class="toast align-items-center text-white bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                  <div class="toast-body">
                   {{message}}
                  </div>
                  <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
              </div>
            {% endfor %}
        {%endif%}  
        <div class="card col-lg-5 col-md-9 col-sm-10 p-5">
            <h3 class="text-center">PROFILE</h3>
            <form action="{% url 'patient:p_profile' %}" method="post" enctype="multipart/form-data">
                {%csrf_token%}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary" >Submit</button>
            </form>
        </div>
    </div>
</div>            

{%endblock%}

patient/templates/check.html
{% extends "user-admin.html" %}


{% block 'content' %}
{% load filt%}
{% load patient%}
<!-- <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css"> -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<div class="d-flex  justify-content-center align-items-center h-100 w-100">
 
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


{% if messages %}
       
          
{% for message in messages %}
     {% if message.tags == 'error'%}
         <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
         <script>
             var m="{{message}}";
             console.log(m);
             Swal.fire({
                     position: 'center',
                     icon: 'error',
                     title: m,
                     showConfirmButton: false,
                     timer: 3000
                     })
            </script>
            {%endif%}
     {% if message.tags == 'success'%}
            <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
            <script>
                var m="{{message}}";
                console.log(m);
                Swal.fire({
                        position: 'center',
                        icon: 'success',
                        title: m,
                        showConfirmButton: false,
                        timer: 7000
                        })
               </script>
               {%endif%}       
{% endfor %}
{%endif%}     <div class="card bg-transBody p-5" style="width: 90%; height: 90%;">   
                

                <form action="{% url 'patient:d_order' id=id %}" method="post" class="checkout__form">{%csrf_token%}  
                  <div class="row d-flex  justify-content-center ">
                    <div class="col-lg-8 col-sm-6 ">
                      <h5 class="text-center text-transform">Billing detail</h5> 
                      <div class="card p-2 bg-transBody">
                        <div class="d-flex justify-content-between p-0">
                          <h5 class="ml-4 p-0">Address</h5>
                          <a href="{% url 'patient:adres' id=id %}" class="float-right p-0"><i class="bi bi-plus-lg  mr-4"></i></a>
                        </div>
                        {%if adress%}  
                   
                          {% for ads in adress %}
                            <div class="card" style="background-color: transparent; border: none;"> 
                                <div class="row">
                                  <div class="col-1 pt-2">
                                      <input type="radio" name="address" id="address{{ ads.id }}" value="{{ ads.id }}" required>
                                      <label for="address{{ ads.id }}"></label>
                                  </div>
                                  <div class="col-11">

                                  <div class="d-flex justify-content-between">
                                    <div>
                                      {{ ads.address }}<br>{{ ads.city }}<br>{{ ads.state }}<br>{{ ads.Pin_code }}

                                    </div>
                                    <div class="d-flex flex-column justify-content-end" >
                                      <a href="{% url 'patient:edit_adres' ads.id id %}" class="float-right px-1"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                      <a href="{% url 'patient:delete_adres' ads.id id %}" class="float-right "><i class="fa fa-trash" aria-hidden="true"></i></a>                                                      
                                    </div>
                                  </div>  
                                  </div>
                                </div>
                            </div>   
                          {% endfor %}
                        {%endif%}
                      </div>
                    </div>    
                    <div class="col-lg-4 col-sm-6 ">
                      <div class="card mt-4 p-4 bg-transBody">
                        <h5 class="text-center">Your order</h5>
                        <div class="">
                                {% for i in list%}
                                    <h6 name="product" class="ml-3">{{i.medicine}} <span name="total" class="text-dark float-right mr-2">$ {{i.medicine.price|ttl:i.quantity}}</span></h6>   
                                {%endfor%} 
                        </div>
                        <div class="">
                                {% if request.session.coupen %}
                                  <h5 class="ml-3 mt-2 mb-2">Total <span class="float-right mr-2  ">$ {{money}}</span></h5>
                                  <h5 class="ml-3 mt-2 mb-2">Discount Price<span class="float-right">$ {{request.session.coupen|discount}}<a href="{% url 'patient:delet_coupen' id=id %}" class="bg-light rounded"><i class="text-white bi bi-x"></i></a></span></h5>
                                  <h5 class="ml-3 mt-2 mb-2">Total <span class="float-right mr-2  ">$ {{money|summery:request.session.coupen}}</span></h5> 
                                {%else%}
                                
                                   <h5 class="ml-3 mt-2 mb-2">Total <span class="float-right mr-2  ">$ {{money}}</span></h5>
                                {%endif%}            
                        
                        </div>

                        <div class="ml-3">
                            <input type="radio" name="payment" id="cash" value="cash"   required>
                            <label for="cash">Cash on delivery</label><br>
                            <input type="radio" name="payment" id="online" value="online" required>
                            <label for="online">Online Payment</label><br>
                            {% if request.session.coupen %}
                               <input type="radio" name="payment" id="wallet" value="wallet" {% if money|summery:request.session.coupen > walt %} disabled {%endif%} required>
                            {%else%}
                              <input type="radio" name="payment" id="wallet" value="wallet" {% if money > walt %} disabled {%endif%} required>
                              
                            {%endif%}
                            <label for="wallet">wallet</label>  
                               
                        </div>
                        
                        <div class="checkout__order__widget ml-3">
                            <input type="checkbox" id="paypal">
                            <label for="paypal">
                                PayPal
                            </label>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-ligth text-success w-50">Place oder</button>

                        </div>
                      </div>
                    </div>
                  </div>  
                </form>
                <div class="card col-xl-4 col-lg-6 col-sm-10 col-xs-12 bg-transBody discbody">
                  <h4 class="coupen_data text-center">coupen codes</h4>
                  <div class="d-flex flex-column align-item-center p-3 disc" style=" animation-duration: 5s;">
                    <form action="{% url 'patient:copn' id=id %}" method="post">
                        {%csrf_token%}
                        <input type="text" class="border border-0 rounded-4 px-3  w-100 pl-5 bg-transBody" 
                        style="height:40px;outline: none;" name="coupon" placeholder="Enter your coupon code">
                        <div class="py-2 mx-2">
                            <button class="btn bg-transBody" type="submit" class="dibut">Apply</button>
                        </div>
                    </form>
                  </div>  
                </div>   
              </div>  
        <script>
          //  const coupenShow=document.querySelector('.disc')

          // window.addEventListener('load', function(){
          //   coupenShow.classList.add('d-none')
          // });
    
           $(document).ready(function(){
            const $coupenShow = $('.disc');
            $coupenShow.addClass('d-none'); 
             $(".coupen_data").click(function () {
            if ($coupenShow.hasClass('d-none')) {
              $coupenShow.fadeIn('slow').removeClass('d-none')
            } else {
                $coupenShow.fadeOut('slow').addClass('d-none')
            }
            });

         });   
       </script>
  </div>


 {%endblock%}   

patient/templates/ed_address.html
{% extends "user-admin.html" %}

{%load crispy_forms_tags %} 

{% block 'content' %}

               <div class="container row h-100 w-100 my-3">

                <div class="col-lg-6 col-md-9 col-sm-10 d-flex justify-content-center align-items-center w-100">
                   <div class="card p-3 px-5 mx-5 bg-transBody w-50">
                        <h3 class="text-center text-uppercase">ADD address</h3>
                        <form action="{% url 'patient:edit_adres' id item %}" method="post"  >
                                {% csrf_token %}
                                {{form|crispy}}
                                <div class="text-center">
                                        <button class="btn btn-primary mt-2 w-50" type="submit">submit</button>

                                </div>
                        </form>
                  </div>
                </div>
        </div> 

{%endblock%}

patient/templates/myorder_hs.html
{% extends "user-admin.html" %}

{% load patient%}
{% block 'content' %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>

  <div class="container d-flex justify-content-center align-items-center h-100 w-100 " 
  style="background-color:transparent ;">
                 
    {% if messages%}                  
    {% for message in messages %}
    {% if message.tags == 'error'%}
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script>
            var m="{{message}}";
            console.log(m);
            Swal.fire({
                    position: 'center',
                    icon: 'error',
                    title: m,
                    showConfirmButton: false,
                    timer: 4000
                    })
           </script>
           {%endif%}
    {% if message.tags == 'success'%}
           <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
           <script>
               var m="{{message}}";
               console.log(m);
               Swal.fire({
                       position: 'center',
                       icon: 'success',
                       title: m,
                       showConfirmButton: false,
                       timer: 4500
                       })
              </script>
              {%endif%}       
{% endfor %}
{%endif%} 
    <div class="card p-3 pl-5  " style="width: 90%; height: 95%; background-color: transparent;border: none;">
      <div class="card-title shadow-lg p-2 bg-transBody rounded d-flex justify-content-between">
        <h3 class=" pl-2">ORDER HISTORY</h3>
        <a href="{% url 'patient:ord' %}" class="btn btn-warning rounded-3 float-right px-2">my order</a>
      </div>
    <div class="row"> 
        <div class="col-lg-6  mt-3">
                {% for i in order_list%}
                 <div class="card mt-2  p-3 text-white bg-transBody">
                   <table>
                     <tbody>
                      <tr>
                        <td class="d-flex justify-content-around">
                          <div>
                            <h6>Bill number</h6>
                            <h6>Order date</h6>
                            <h6>Product name</h6>
                            <h6>Product Quantity</h6>
                            <h6>Amount</h6>
                            <h6>Payment Type</h6>
                            <h6>order status</h6>
                         </div>
                         <div>
                            <h6>#{{i.id}}{{i.order_date.day}}{{i.order_date.year}}</h6>
                            <h6>{{i.order_date}}</h6>
                            {% if i.order_items.exists %}
                                <h6>{{ i.order_items.first.product }}</h6>
                                <h6>{{ i.order_items.first.quantity }}</h6>
                            {% endif %}
                            <h6>{{i.Total_Price}}</h6>
                            <h6>{{i.Pay_option}}</h6>                      
                            <h6>{{i.status}}</h6>
                         </div>    
                          <!-- #{{i.id}}{{i.order_date.day}}{{i.order_date.year}}<br>
                          {{i.order_date}}<br>
                          {% for j in i.order_items.all%}              
                             {{j.product}} {{j.quantity}}
                          {%endfor%}
                          <br>
                          {{i.Total_Price}}<br>
                          {{i.Pay_option}}<br>                      
                          {{i.status}}
                        </td> -->
                        <td>
                          {% for j in i.order_items.all%}              
                            <img src="{{j.product.image.url}}" width="100px" height="100px"> 
                          {%endfor%}
                        </td>
                      </tr>
                     </tbody>
                   </table>
                    
                     <div class="text-center">
                    {% if i.order_refund.all %}
                        {% for k in i.order_refund.all %}
                          {% if k.status == "completed" %} 
                             <a class="btn btn-primary">Return completed</a>
                          {% elif k.status == "cancel" %}
                             <a class="btn text-danger">Return Revoked</a>                          
                          {% else%} 
                             <a class="btn btn-warning w-50" >Return {{k.status}}</a>
                          {%endif%}   
                        {%endfor%}          
                    {%else%}
                      {% if i.order_date.date|expaire %}
                         <a class="return  btn btn-danger bg-danger" data-item-id="{{i.id}}" value="{{ i.id }}">return</a> 
                         <!-- <a href="#" class="btn btn-primary">Return</a> -->
                         <a href="{% url 'patient:invoice' i.id %}" class="btn btn-info">Invoice</a>   
                      {%else%}
                         <a href="{% url 'patient:invoice' i.id %}" class="btn btn-info">Invoice</a>   
                      {%endif%}
                    {%endif%}  
                      </div>
                 </div>
                {%endfor%} 
        </div>
    </div>  
  </div>
  <div class="modal fade" id="deleteModal3" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
      <form action="{% url 'patient:cancel_order' %}" method="post">
        {% csrf_token %} 
          <div class="modal-header text-center">
            <h4 class="modal-title text-dark w-100" id="deleteModalLabel">RETURN ORDER</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body ">
              <input type="hidden" name="dele" id="userdel_id"  value="">
              <h6 class="text-center text-dark">Are you really want to return the order</h6>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-danger" id="confirmDelete">Yes</button>
          </div>
      </form>  
      </div>
    </div>
</div>
<script>
  $(document).ready(function(){                  
  $('.return').click(function(e){
    e.preventDefault();
    var id = $(this).attr("value");
    // id = $(".delete-button").attr("value");
    console.log(id);
    $('#userdel_id').val(id);
    $('#deleteModal3').modal('show');
  });
});
</script>     
  </div>              


{%endblock%}